Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -69,7 +69,8 @@ jobs:
           
       - name: list files in release folder
         run: ls ${{steps.pwd_step.outputs.current_dir}}/release
-        
+      - name: Check Body Contents
+        run: cat /release/body.md
 
       - name: Bump version and push tag
         id: tag_version
@@ -96,8 +97,31 @@ jobs:
   build:
     name: Build my project ✨
     runs-on: ubuntu-latest
-
     steps:
+      - name: Check if the pull request was merged
+        id: check_merge
+        run: |
+          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
+            echo "Pull request was merged!"
+            echo "::set-output name=pr_body::${{ github.event.pull_request.body }}"
+          else
+            echo "Error: Pull request to main branch was closed but not merged."
+            exit 1
+          fi
+      - name: create body.md
+        uses: 1arp/create-a-file-action@0.2
+        with:            
+          path: /release
+          file: body.md
+            # The content of the file
+          content: ${{ steps.check_merge.outputs.pr_body }}
+      - name: Check Body Contents
+        run: cat /release/body.md
+          
+      - name: list files in release folder
+        run: ls ${{steps.pwd_step.outputs.current_dir}}/release
+      - name: Check Body Contents
+        run: cat /release/body.md
       # Checkout
       - name: Checkout repository
         uses: actions/checkout@v3
